ALTER TABLE shift_logs
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

ALTER TABLE run_logs
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

ALTER TABLE downtime_logs
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
